### ISSUE TITLE
随机任务排队显示问题

### ISSUE THREAD

**Issue by idenpa** [DieMoe233/DFAssist_CN#13]
4.5之后，随机任务排队顺序永远显示是1，虽然日志里可以显示正常，如图所示。
![Snipaste_2019-06-12_09-07-30](https://user-images.githubusercontent.com/1414904/59316596-d7615d00-8cf1-11e9-85b1-5765fd92264e.png)
![Snipaste_2019-06-12_09-09-17](https://user-images.githubusercontent.com/1414904/59316609-e21bf200-8cf1-11e9-8416-60fbeca36936.png)
版本是0528.1最新版

**Comment by DieMoe233** [comment]
Fixed，请尝试稍后的版本推送，或直接下载github上最新的release。

**Comment by idenpa** [comment]
感谢修复 新版已经正常~
