### ISSUE TITLE
CheatRoulette = True

### ISSUE THREAD

**Issue by lyl632** [DieMoe233/DFAssist_CN#17]
这个参数我尝试在源码\App\Settings.cs中修改后，用Visual Studio 2019生成了\App\bin\Release\DFAssist.exe，在我编程的电脑中测试时可以“破解版”提示。

但当我将此程序发送到我装有FF14的电脑上测试时，程序的版本变成了普通版，高级功能不可选。我装有FF14的电脑上之前运行过DFAssist的普通版。请问此程序是否在本地保存其他信息从而使我对源码的修改无效，这样的问题该如何处理。

**Comment by zhaojiaheng0115** [comment]
能指导一下如何修改吗？对程序方面不是很熟悉，用vscode不知道如何打包……

**Comment by lyl632** [comment]
> 能指导一下如何修改吗？对程序方面不是很熟悉，用vscode不知道如何打包……

vscode只是编辑器
