### ISSUE TITLE
恒冰的  雪之女王 貌似没有TTS声音提示

### ISSUE THREAD

**Issue by wingchaos** [DieMoe233/DFAssist_CN#7]
不知道是我个人问题还是咋。。其他NM是没问题会TTS发声提示的。就只有20NM 雪之女王（]FATE: Eternity FATE出现！）莫得声音提示

**Comment by wingchaos** [comment]
嗷还有。先一波感谢提供了软件。

**Comment by DieMoe233** [comment]
试着清空一下TTS缓存可能会有效果。
